---
title: "06.24.2020_Summary_Stats"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Libraries and read in the ncessary data
```{r}
database<-read.csv("data_filtered_complete.csv",header = TRUE)
library(tidyverse)
library(dbplyr)
library(caret)
library(fastDummies)
database<-subset(database,select=-c(X))
# filter out extremities
database<-database %>% filter(price<1000&actual_eps<100&average_forecasted_earnings<100)
database
```
# Find out how many years of data per company
```{r}
unique_database_ticker<-database %>% distinct(ticker,.keep_all = TRUE)
mean(unique_database_ticker$number_of_years)
unique_database_ticker
```

# Assign Bear and Bull Years
```{r}
database$bull<-'true'
database$bull[database$year_analyst_predict==1987]<-'false'
database$bull[database$year_analyst_predict==1990]<-'false'
database$bull[database$year_analyst_predict==2000]<-'false'
database$bull[database$year_analyst_predict==2001]<-'false'
database$bull[database$year_analyst_predict==2002]<-'false'
database$bull[database$year_analyst_predict==2008]<-'false'
database$bull[database$year_analyst_predict==2009]<-'false'
```
# Quartile by January of the year by scaled feps
```{r}
january_only_database<-database %>% filter(month_analyst_predict==1)
january_only_database<-january_only_database %>% group_by(year_analyst_predict) %>% mutate(quartile_feps = ntile(scaled_feps,4))
january_only_database<-january_only_database %>% group_by(year_analyst_predict) %>% mutate(quartile_market_capitalization = ntile(market_capitalization,4))
january_only_database
```
# Parse the result into just years
```{r}
january_only_database_v1<-subset(january_only_database,select=c(ticker,year_analyst_predict,quartile_feps,quartile_market_capitalization))
database_v1<-inner_join(database,january_only_database_v1,by=c('ticker'='ticker','year_analyst_predict'='year_analyst_predict'))  
database_v1<-unique(database_v1)
database_v1<-arrange(database_v1,ticker,year_analyst_predict,month_analyst_predict)
database_v1
```
# Adjust analyst estimates to highest in the year
```{r}
database_v1<-database_v1 %>% group_by(ticker,year_analyst_predict) %>% mutate(max_num_est_per_year=max(num_est))
write.csv(database_v1,"database_for_sum_stats.csv")
```
# Summary stats for the entire table and then by year
```{r}
x <- c("Overall","Q1","Q2","Q3","Q4")
y <- c("number_of_analysts","forecasted_earnings","actual_earnings","scaled_forecast","price","market_value")
# Creation of the table 
# Define MC Table
stock_database_quartiled_mc_table<- data.frame(matrix(ncol = 5, nrow = 6))
colnames(stock_database_quartiled_mc_table) <- x
rownames(stock_database_quartiled_mc_table)<-y
# Define FEPS Table
stock_database_quartiled_feps_table <- data.frame(matrix(ncol = 5, nrow = 6))
colnames(stock_database_quartiled_feps_table) <- x
rownames(stock_database_quartiled_feps_table)<-y

# Define the quartiles
quartile_one <-database_v1%>% filter(quartile_market_capitalization==1)
quartile_two<-database_v1 %>% filter (quartile_market_capitalization==2)
quartile_three<-database_v1 %>% filter (quartile_market_capitalization==3)
quartile_four<-database_v1 %>% filter (quartile_market_capitalization==4)

# Define the quartiles as January
base_predict_month_quartile_one <-january_only_database %>% filter (quartile_market_capitalization ==1)
base_predict_month_quartile_two <-january_only_database %>% filter (quartile_market_capitalization ==2)
base_predict_month_quartile_three <-january_only_database %>% filter (quartile_market_capitalization ==3)
base_predict_month_quartile_four <-january_only_database %>% filter (quartile_market_capitalization ==4)
# Number of Analysts using actual mean 
# stock_database_1980_1996_quartiled_mc_table[1,1]<-mean(distinct_quartiled_1980_1996$number_of_analyst_predictions)
# stock_database_1980_1996_quartiled_mc_table[1,2]<-mean(quartile_one$number_of_analyst_predictions)
# stock_database_1980_1996_quartiled_mc_table[1,3]<-mean(quartile_two$number_of_analyst_predictions)
# stock_database_1980_1996_quartiled_mc_table[1,4]<-mean(quartile_three$number_of_analyst_predictions)
# stock_database_1980_1996_quartiled_mc_table[1,5]<-mean(quartile_four$number_of_analyst_predictions)
stock_database_quartiled_mc_table[1,1]<-mean(database_v1$max_num_est_per_year)
stock_database_quartiled_mc_table[1,2]<-mean(quartile_one$max_num_est_per_year)
stock_database_quartiled_mc_table[1,3]<-mean(quartile_two$max_num_est_per_year)
stock_database_quartiled_mc_table[1,4]<-mean(quartile_three$max_num_est_per_year)
stock_database_quartiled_mc_table[1,5]<-mean(quartile_four$max_num_est_per_year)
# forecasted_earnings
stock_database_quartiled_mc_table[2,1]<-mean(database_v1$average_forecasted_earnings)
stock_database_quartiled_mc_table[2,2]<-mean(quartile_one$average_forecasted_earnings)
stock_database_quartiled_mc_table[2,3]<-mean(quartile_two$average_forecasted_earnings)
stock_database_quartiled_mc_table[2,4]<-mean(quartile_three$average_forecasted_earnings)
stock_database_quartiled_mc_table[2,5]<-mean(quartile_four$average_forecasted_earnings)
# Actual Earnings
stock_database_quartiled_mc_table[3,1]<-mean(database_v1$actual_eps)
stock_database_quartiled_mc_table[3,2]<-mean(quartile_one$actual_eps)
stock_database_quartiled_mc_table[3,3]<-mean(quartile_two$actual_eps)
stock_database_quartiled_mc_table[3,4]<-mean(quartile_three$actual_eps)
stock_database_quartiled_mc_table[3,5]<-mean(quartile_four$actual_eps)
# FEPS
stock_database_quartiled_mc_table[4,1]<-mean(january_only_database$scaled_feps)
stock_database_quartiled_mc_table[4,2]<-mean(base_predict_month_quartile_one$scaled_feps)
stock_database_quartiled_mc_table[4,3]<-mean(base_predict_month_quartile_two$scaled_feps)
stock_database_quartiled_mc_table[4,4]<-mean(base_predict_month_quartile_three$scaled_feps)
stock_database_quartiled_mc_table[4,5]<-mean(base_predict_month_quartile_four$scaled_feps)
# Price 
stock_database_quartiled_mc_table[5,1]<-mean(database_v1$price)
stock_database_quartiled_mc_table[5,2]<-mean(quartile_one$price)
stock_database_quartiled_mc_table[5,3]<-mean(quartile_two$price)
stock_database_quartiled_mc_table[5,4]<-mean(quartile_three$price)
stock_database_quartiled_mc_table[5,5]<-mean(quartile_four$price)
# Market Cap 
stock_database_quartiled_mc_table[6,1]<-mean(database_v1$market_capitalization)
stock_database_quartiled_mc_table[6,2]<-mean(quartile_one$market_capitalization)
stock_database_quartiled_mc_table[6,3]<-mean(quartile_two$market_capitalization)
stock_database_quartiled_mc_table[6,4]<-mean(quartile_three$market_capitalization)
stock_database_quartiled_mc_table[6,5]<-mean(quartile_four$market_capitalization)

# Define the quartiles
quartile_one <-database_v1%>% filter(quartile_feps==1)
quartile_two<-database_v1 %>% filter (quartile_feps==2)
quartile_three<-database_v1 %>% filter (quartile_feps==3)
quartile_four<-database_v1 %>% filter (quartile_feps==4)
# Define the quartiles as of January
base_predict_month_quartile_one <-january_only_database %>% filter (quartile_feps==1)
base_predict_month_quartile_two <-january_only_database %>% filter (quartile_feps==2)
base_predict_month_quartile_three <-january_only_database %>% filter (quartile_feps==3)
base_predict_month_quartile_four <-january_only_database %>% filter (quartile_feps==4)
# Number of Analysts
# stock_database_quartiled_feps_table[1,1]<-mean(distinct_quartiled_1980_1996$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,2]<-mean(quartile_one$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,3]<-mean(quartile_two$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,4]<-mean(quartile_three$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,5]<-mean(quartile_four$number_of_analyst_predictions)
stock_database_quartiled_feps_table[1,1]<-mean(database_v1$max_num_est_per_year)
stock_database_quartiled_feps_table[1,2]<-mean(quartile_one$max_num_est_per_year)
stock_database_quartiled_feps_table[1,3]<-mean(quartile_two$max_num_est_per_year)
stock_database_quartiled_feps_table[1,4]<-mean(quartile_three$max_num_est_per_year)
stock_database_quartiled_feps_table[1,5]<-mean(quartile_four$max_num_est_per_year)
# forecasted_earnings
stock_database_quartiled_feps_table[2,1]<-mean(database_v1$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,2]<-mean(quartile_one$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,3]<-mean(quartile_two$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,4]<-mean(quartile_three$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,5]<-mean(quartile_four$average_forecasted_earnings)
# Actual Earnings
stock_database_quartiled_feps_table[3,1]<-mean(database_v1$actual_eps)
stock_database_quartiled_feps_table[3,2]<-mean(quartile_one$actual_eps)
stock_database_quartiled_feps_table[3,3]<-mean(quartile_two$actual_eps)
stock_database_quartiled_feps_table[3,4]<-mean(quartile_three$actual_eps)
stock_database_quartiled_feps_table[3,5]<-mean(quartile_four$actual_eps)
# FEPS
stock_database_quartiled_feps_table[4,1]<-mean(january_only_database$scaled_feps)
stock_database_quartiled_feps_table[4,2]<-mean(base_predict_month_quartile_one$scaled_feps)
stock_database_quartiled_feps_table[4,3]<-mean(base_predict_month_quartile_two$scaled_feps)
stock_database_quartiled_feps_table[4,4]<-mean(base_predict_month_quartile_three$scaled_feps)
stock_database_quartiled_feps_table[4,5]<-mean(base_predict_month_quartile_four$scaled_feps)
# Price 
stock_database_quartiled_feps_table[5,1]<-mean(database_v1$price)
stock_database_quartiled_feps_table[5,2]<-mean(quartile_one$price)
stock_database_quartiled_feps_table[5,3]<-mean(quartile_two$price)
stock_database_quartiled_feps_table[5,4]<-mean(quartile_three$price)
stock_database_quartiled_feps_table[5,5]<-mean(quartile_four$price)
# Market Cap 
stock_database_quartiled_feps_table[6,1]<-mean(database_v1$market_capitalization)
stock_database_quartiled_feps_table[6,2]<-mean(quartile_one$market_capitalization)
stock_database_quartiled_feps_table[6,3]<-mean(quartile_two$market_capitalization)
stock_database_quartiled_feps_table[6,4]<-mean(quartile_three$market_capitalization)
stock_database_quartiled_feps_table[6,5]<-mean(quartile_four$market_capitalization)

# Save the tables
write.csv(stock_database_quartiled_feps_table,"entire_period_stock_database_quartiled_feps_table.csv")
write.csv(stock_database_quartiled_mc_table,"entire_period_stock_database_quartiled_mc_table.csv")
```
# Summary stats for the for 1980 - 1996
```{r}
first_partition<-database_v1 %>% filter(year_analyst_predict<=1996)
first_partition_jan<-january_only_database %>% filter(year_analyst_predict<=1996)

x <- c("Overall","Q1","Q2","Q3","Q4")
y <- c("number_of_analysts","forecasted_earnings","actual_earnings","scaled_forecast","price","market_value")
# Creation of the table 
# Define MC Table
stock_database_quartiled_mc_table<- data.frame(matrix(ncol = 5, nrow = 6))
colnames(stock_database_quartiled_mc_table) <- x
rownames(stock_database_quartiled_mc_table)<-y
# Define FEPS Table
stock_database_quartiled_feps_table <- data.frame(matrix(ncol = 5, nrow = 6))
colnames(stock_database_quartiled_feps_table) <- x
rownames(stock_database_quartiled_feps_table)<-y

# Define the quartiles
quartile_one <-first_partition%>% filter(quartile_market_capitalization==1)
quartile_two<-first_partition %>% filter (quartile_market_capitalization==2)
quartile_three<-first_partition %>% filter (quartile_market_capitalization==3)
quartile_four<-first_partition %>% filter (quartile_market_capitalization==4)

# Define the quartiles as January
base_predict_month_quartile_one <-first_partition_jan %>% filter (quartile_market_capitalization ==1)
base_predict_month_quartile_two <-first_partition_jan %>% filter (quartile_market_capitalization ==2)
base_predict_month_quartile_three <-first_partition_jan %>% filter (quartile_market_capitalization ==3)
base_predict_month_quartile_four <-first_partition_jan %>% filter (quartile_market_capitalization ==4)
# Number of Analysts using actual mean 
# stock_database_1980_1996_quartiled_mc_table[1,1]<-mean(distinct_quartiled_1980_1996$number_of_analyst_predictions)
# stock_database_1980_1996_quartiled_mc_table[1,2]<-mean(quartile_one$number_of_analyst_predictions)
# stock_database_1980_1996_quartiled_mc_table[1,3]<-mean(quartile_two$number_of_analyst_predictions)
# stock_database_1980_1996_quartiled_mc_table[1,4]<-mean(quartile_three$number_of_analyst_predictions)
# stock_database_1980_1996_quartiled_mc_table[1,5]<-mean(quartile_four$number_of_analyst_predictions)
stock_database_quartiled_mc_table[1,1]<-mean(first_partition$max_num_est_per_year)
stock_database_quartiled_mc_table[1,2]<-mean(quartile_one$max_num_est_per_year)
stock_database_quartiled_mc_table[1,3]<-mean(quartile_two$max_num_est_per_year)
stock_database_quartiled_mc_table[1,4]<-mean(quartile_three$max_num_est_per_year)
stock_database_quartiled_mc_table[1,5]<-mean(quartile_four$max_num_est_per_year)
# forecasted_earnings
stock_database_quartiled_mc_table[2,1]<-mean(first_partition$average_forecasted_earnings)
stock_database_quartiled_mc_table[2,2]<-mean(quartile_one$average_forecasted_earnings)
stock_database_quartiled_mc_table[2,3]<-mean(quartile_two$average_forecasted_earnings)
stock_database_quartiled_mc_table[2,4]<-mean(quartile_three$average_forecasted_earnings)
stock_database_quartiled_mc_table[2,5]<-mean(quartile_four$average_forecasted_earnings)
# Actual Earnings
stock_database_quartiled_mc_table[3,1]<-mean(first_partition$actual_eps)
stock_database_quartiled_mc_table[3,2]<-mean(quartile_one$actual_eps)
stock_database_quartiled_mc_table[3,3]<-mean(quartile_two$actual_eps)
stock_database_quartiled_mc_table[3,4]<-mean(quartile_three$actual_eps)
stock_database_quartiled_mc_table[3,5]<-mean(quartile_four$actual_eps)
# FEPS
stock_database_quartiled_mc_table[4,1]<-mean(first_partition_jan$scaled_feps)
stock_database_quartiled_mc_table[4,2]<-mean(base_predict_month_quartile_one$scaled_feps)
stock_database_quartiled_mc_table[4,3]<-mean(base_predict_month_quartile_two$scaled_feps)
stock_database_quartiled_mc_table[4,4]<-mean(base_predict_month_quartile_three$scaled_feps)
stock_database_quartiled_mc_table[4,5]<-mean(base_predict_month_quartile_four$scaled_feps)
# Price 
stock_database_quartiled_mc_table[5,1]<-mean(first_partition$price)
stock_database_quartiled_mc_table[5,2]<-mean(quartile_one$price)
stock_database_quartiled_mc_table[5,3]<-mean(quartile_two$price)
stock_database_quartiled_mc_table[5,4]<-mean(quartile_three$price)
stock_database_quartiled_mc_table[5,5]<-mean(quartile_four$price)
# Market Cap 
stock_database_quartiled_mc_table[6,1]<-mean(first_partition$market_capitalization)
stock_database_quartiled_mc_table[6,2]<-mean(quartile_one$market_capitalization)
stock_database_quartiled_mc_table[6,3]<-mean(quartile_two$market_capitalization)
stock_database_quartiled_mc_table[6,4]<-mean(quartile_three$market_capitalization)
stock_database_quartiled_mc_table[6,5]<-mean(quartile_four$market_capitalization)

# Define the quartiles
quartile_one <-first_partition%>% filter(quartile_feps==1)
quartile_two<-first_partition %>% filter (quartile_feps==2)
quartile_three<-first_partition %>% filter (quartile_feps==3)
quartile_four<-first_partition %>% filter (quartile_feps==4)
# Define the quartiles as of January
base_predict_month_quartile_one <-first_partition_jan %>% filter (quartile_feps==1)
base_predict_month_quartile_two <-first_partition_jan %>% filter (quartile_feps==2)
base_predict_month_quartile_three <-first_partition_jan %>% filter (quartile_feps==3)
base_predict_month_quartile_four <-first_partition_jan %>% filter (quartile_feps==4)
# Number of Analysts
# stock_database_quartiled_feps_table[1,1]<-mean(distinct_quartiled_1980_1996$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,2]<-mean(quartile_one$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,3]<-mean(quartile_two$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,4]<-mean(quartile_three$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,5]<-mean(quartile_four$number_of_analyst_predictions)
stock_database_quartiled_feps_table[1,1]<-mean(first_partition$max_num_est_per_year)
stock_database_quartiled_feps_table[1,2]<-mean(quartile_one$max_num_est_per_year)
stock_database_quartiled_feps_table[1,3]<-mean(quartile_two$max_num_est_per_year)
stock_database_quartiled_feps_table[1,4]<-mean(quartile_three$max_num_est_per_year)
stock_database_quartiled_feps_table[1,5]<-mean(quartile_four$max_num_est_per_year)
# forecasted_earnings
stock_database_quartiled_feps_table[2,1]<-mean(first_partition$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,2]<-mean(quartile_one$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,3]<-mean(quartile_two$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,4]<-mean(quartile_three$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,5]<-mean(quartile_four$average_forecasted_earnings)
# Actual Earnings
stock_database_quartiled_feps_table[3,1]<-mean(first_partition$actual_eps)
stock_database_quartiled_feps_table[3,2]<-mean(quartile_one$actual_eps)
stock_database_quartiled_feps_table[3,3]<-mean(quartile_two$actual_eps)
stock_database_quartiled_feps_table[3,4]<-mean(quartile_three$actual_eps)
stock_database_quartiled_feps_table[3,5]<-mean(quartile_four$actual_eps)
# FEPS
stock_database_quartiled_feps_table[4,1]<-mean(first_partition_jan$scaled_feps)
stock_database_quartiled_feps_table[4,2]<-mean(base_predict_month_quartile_one$scaled_feps)
stock_database_quartiled_feps_table[4,3]<-mean(base_predict_month_quartile_two$scaled_feps)
stock_database_quartiled_feps_table[4,4]<-mean(base_predict_month_quartile_three$scaled_feps)
stock_database_quartiled_feps_table[4,5]<-mean(base_predict_month_quartile_four$scaled_feps)
# Price 
stock_database_quartiled_feps_table[5,1]<-mean(first_partition$price)
stock_database_quartiled_feps_table[5,2]<-mean(quartile_one$price)
stock_database_quartiled_feps_table[5,3]<-mean(quartile_two$price)
stock_database_quartiled_feps_table[5,4]<-mean(quartile_three$price)
stock_database_quartiled_feps_table[5,5]<-mean(quartile_four$price)
# Market Cap 
stock_database_quartiled_feps_table[6,1]<-mean(first_partition$market_capitalization)
stock_database_quartiled_feps_table[6,2]<-mean(quartile_one$market_capitalization)
stock_database_quartiled_feps_table[6,3]<-mean(quartile_two$market_capitalization)
stock_database_quartiled_feps_table[6,4]<-mean(quartile_three$market_capitalization)
stock_database_quartiled_feps_table[6,5]<-mean(quartile_four$market_capitalization)

# Save the tables
write.csv(stock_database_quartiled_feps_table,"1980_1996_stock_database_quartiled_feps_table.csv")
write.csv(stock_database_quartiled_mc_table,"1980_1996_stock_database_quartiled_mc_table.csv")
```
# 1997 - 2018
```{r}
first_partition<-database_v1 %>% filter(year_analyst_predict>1996)
first_partition_jan<-january_only_database %>% filter(year_analyst_predict>1996)

x <- c("Overall","Q1","Q2","Q3","Q4")
y <- c("number_of_analysts","forecasted_earnings","actual_earnings","scaled_forecast","price","market_value")
# Creation of the table 
# Define MC Table
stock_database_quartiled_mc_table<- data.frame(matrix(ncol = 5, nrow = 6))
colnames(stock_database_quartiled_mc_table) <- x
rownames(stock_database_quartiled_mc_table)<-y
# Define FEPS Table
stock_database_quartiled_feps_table <- data.frame(matrix(ncol = 5, nrow = 6))
colnames(stock_database_quartiled_feps_table) <- x
rownames(stock_database_quartiled_feps_table)<-y

# Define the quartiles
quartile_one <-first_partition%>% filter(quartile_market_capitalization==1)
quartile_two<-first_partition %>% filter (quartile_market_capitalization==2)
quartile_three<-first_partition %>% filter (quartile_market_capitalization==3)
quartile_four<-first_partition %>% filter (quartile_market_capitalization==4)

# Define the quartiles as January
base_predict_month_quartile_one <-first_partition_jan %>% filter (quartile_market_capitalization ==1)
base_predict_month_quartile_two <-first_partition_jan %>% filter (quartile_market_capitalization ==2)
base_predict_month_quartile_three <-first_partition_jan %>% filter (quartile_market_capitalization ==3)
base_predict_month_quartile_four <-first_partition_jan %>% filter (quartile_market_capitalization ==4)
# Number of Analysts using actual mean 
# stock_database_1980_1996_quartiled_mc_table[1,1]<-mean(distinct_quartiled_1980_1996$number_of_analyst_predictions)
# stock_database_1980_1996_quartiled_mc_table[1,2]<-mean(quartile_one$number_of_analyst_predictions)
# stock_database_1980_1996_quartiled_mc_table[1,3]<-mean(quartile_two$number_of_analyst_predictions)
# stock_database_1980_1996_quartiled_mc_table[1,4]<-mean(quartile_three$number_of_analyst_predictions)
# stock_database_1980_1996_quartiled_mc_table[1,5]<-mean(quartile_four$number_of_analyst_predictions)
stock_database_quartiled_mc_table[1,1]<-mean(first_partition$max_num_est_per_year)
stock_database_quartiled_mc_table[1,2]<-mean(quartile_one$max_num_est_per_year)
stock_database_quartiled_mc_table[1,3]<-mean(quartile_two$max_num_est_per_year)
stock_database_quartiled_mc_table[1,4]<-mean(quartile_three$max_num_est_per_year)
stock_database_quartiled_mc_table[1,5]<-mean(quartile_four$max_num_est_per_year)
# forecasted_earnings
stock_database_quartiled_mc_table[2,1]<-mean(first_partition$average_forecasted_earnings)
stock_database_quartiled_mc_table[2,2]<-mean(quartile_one$average_forecasted_earnings)
stock_database_quartiled_mc_table[2,3]<-mean(quartile_two$average_forecasted_earnings)
stock_database_quartiled_mc_table[2,4]<-mean(quartile_three$average_forecasted_earnings)
stock_database_quartiled_mc_table[2,5]<-mean(quartile_four$average_forecasted_earnings)
# Actual Earnings
stock_database_quartiled_mc_table[3,1]<-mean(first_partition$actual_eps)
stock_database_quartiled_mc_table[3,2]<-mean(quartile_one$actual_eps)
stock_database_quartiled_mc_table[3,3]<-mean(quartile_two$actual_eps)
stock_database_quartiled_mc_table[3,4]<-mean(quartile_three$actual_eps)
stock_database_quartiled_mc_table[3,5]<-mean(quartile_four$actual_eps)
# FEPS
stock_database_quartiled_mc_table[4,1]<-mean(first_partition_jan$scaled_feps)
stock_database_quartiled_mc_table[4,2]<-mean(base_predict_month_quartile_one$scaled_feps)
stock_database_quartiled_mc_table[4,3]<-mean(base_predict_month_quartile_two$scaled_feps)
stock_database_quartiled_mc_table[4,4]<-mean(base_predict_month_quartile_three$scaled_feps)
stock_database_quartiled_mc_table[4,5]<-mean(base_predict_month_quartile_four$scaled_feps)
# Price 
stock_database_quartiled_mc_table[5,1]<-mean(first_partition$price)
stock_database_quartiled_mc_table[5,2]<-mean(quartile_one$price)
stock_database_quartiled_mc_table[5,3]<-mean(quartile_two$price)
stock_database_quartiled_mc_table[5,4]<-mean(quartile_three$price)
stock_database_quartiled_mc_table[5,5]<-mean(quartile_four$price)
# Market Cap 
stock_database_quartiled_mc_table[6,1]<-mean(first_partition$market_capitalization)
stock_database_quartiled_mc_table[6,2]<-mean(quartile_one$market_capitalization)
stock_database_quartiled_mc_table[6,3]<-mean(quartile_two$market_capitalization)
stock_database_quartiled_mc_table[6,4]<-mean(quartile_three$market_capitalization)
stock_database_quartiled_mc_table[6,5]<-mean(quartile_four$market_capitalization)

# Define the quartiles
quartile_one <-first_partition%>% filter(quartile_feps==1)
quartile_two<-first_partition %>% filter (quartile_feps==2)
quartile_three<-first_partition %>% filter (quartile_feps==3)
quartile_four<-first_partition %>% filter (quartile_feps==4)
# Define the quartiles as of January
base_predict_month_quartile_one <-first_partition_jan %>% filter (quartile_feps==1)
base_predict_month_quartile_two <-first_partition_jan %>% filter (quartile_feps==2)
base_predict_month_quartile_three <-first_partition_jan %>% filter (quartile_feps==3)
base_predict_month_quartile_four <-first_partition_jan %>% filter (quartile_feps==4)
# Number of Analysts
# stock_database_quartiled_feps_table[1,1]<-mean(distinct_quartiled_1980_1996$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,2]<-mean(quartile_one$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,3]<-mean(quartile_two$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,4]<-mean(quartile_three$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,5]<-mean(quartile_four$number_of_analyst_predictions)
stock_database_quartiled_feps_table[1,1]<-mean(first_partition$max_num_est_per_year)
stock_database_quartiled_feps_table[1,2]<-mean(quartile_one$max_num_est_per_year)
stock_database_quartiled_feps_table[1,3]<-mean(quartile_two$max_num_est_per_year)
stock_database_quartiled_feps_table[1,4]<-mean(quartile_three$max_num_est_per_year)
stock_database_quartiled_feps_table[1,5]<-mean(quartile_four$max_num_est_per_year)
# forecasted_earnings
stock_database_quartiled_feps_table[2,1]<-mean(first_partition$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,2]<-mean(quartile_one$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,3]<-mean(quartile_two$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,4]<-mean(quartile_three$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,5]<-mean(quartile_four$average_forecasted_earnings)
# Actual Earnings
stock_database_quartiled_feps_table[3,1]<-mean(first_partition$actual_eps)
stock_database_quartiled_feps_table[3,2]<-mean(quartile_one$actual_eps)
stock_database_quartiled_feps_table[3,3]<-mean(quartile_two$actual_eps)
stock_database_quartiled_feps_table[3,4]<-mean(quartile_three$actual_eps)
stock_database_quartiled_feps_table[3,5]<-mean(quartile_four$actual_eps)
# FEPS
stock_database_quartiled_feps_table[4,1]<-mean(first_partition_jan$scaled_feps)
stock_database_quartiled_feps_table[4,2]<-mean(base_predict_month_quartile_one$scaled_feps)
stock_database_quartiled_feps_table[4,3]<-mean(base_predict_month_quartile_two$scaled_feps)
stock_database_quartiled_feps_table[4,4]<-mean(base_predict_month_quartile_three$scaled_feps)
stock_database_quartiled_feps_table[4,5]<-mean(base_predict_month_quartile_four$scaled_feps)
# Price 
stock_database_quartiled_feps_table[5,1]<-mean(first_partition$price)
stock_database_quartiled_feps_table[5,2]<-mean(quartile_one$price)
stock_database_quartiled_feps_table[5,3]<-mean(quartile_two$price)
stock_database_quartiled_feps_table[5,4]<-mean(quartile_three$price)
stock_database_quartiled_feps_table[5,5]<-mean(quartile_four$price)
# Market Cap 
stock_database_quartiled_feps_table[6,1]<-mean(first_partition$market_capitalization)
stock_database_quartiled_feps_table[6,2]<-mean(quartile_one$market_capitalization)
stock_database_quartiled_feps_table[6,3]<-mean(quartile_two$market_capitalization)
stock_database_quartiled_feps_table[6,4]<-mean(quartile_three$market_capitalization)
stock_database_quartiled_feps_table[6,5]<-mean(quartile_four$market_capitalization)

# Save the tables
write.csv(stock_database_quartiled_feps_table,"1997_2018_stock_database_quartiled_feps_table.csv")
write.csv(stock_database_quartiled_mc_table,"1997_2018_stock_database_quartiled_mc_table.csv")
```
# Bull
```{r}
first_partition<-database_v1 %>% filter(bull=='true')
first_partition_jan<-january_only_database %>% filter(bull=='true')

x <- c("Overall","Q1","Q2","Q3","Q4")
y <- c("number_of_analysts","forecasted_earnings","actual_earnings","scaled_forecast","price","market_value")
# Creation of the table 

# Define FEPS Table
stock_database_quartiled_feps_table <- data.frame(matrix(ncol = 5, nrow = 6))
colnames(stock_database_quartiled_feps_table) <- x
rownames(stock_database_quartiled_feps_table)<-y

# Define the quartiles
quartile_one <-first_partition%>% filter(quartile_feps==1)
quartile_two<-first_partition %>% filter (quartile_feps==2)
quartile_three<-first_partition %>% filter (quartile_feps==3)
quartile_four<-first_partition %>% filter (quartile_feps==4)
# Define the quartiles as of January
base_predict_month_quartile_one <-first_partition_jan %>% filter (quartile_feps==1)
base_predict_month_quartile_two <-first_partition_jan %>% filter (quartile_feps==2)
base_predict_month_quartile_three <-first_partition_jan %>% filter (quartile_feps==3)
base_predict_month_quartile_four <-first_partition_jan %>% filter (quartile_feps==4)
# Number of Analysts
# stock_database_quartiled_feps_table[1,1]<-mean(distinct_quartiled_1980_1996$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,2]<-mean(quartile_one$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,3]<-mean(quartile_two$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,4]<-mean(quartile_three$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,5]<-mean(quartile_four$number_of_analyst_predictions)
stock_database_quartiled_feps_table[1,1]<-mean(first_partition$max_num_est_per_year)
stock_database_quartiled_feps_table[1,2]<-mean(quartile_one$max_num_est_per_year)
stock_database_quartiled_feps_table[1,3]<-mean(quartile_two$max_num_est_per_year)
stock_database_quartiled_feps_table[1,4]<-mean(quartile_three$max_num_est_per_year)
stock_database_quartiled_feps_table[1,5]<-mean(quartile_four$max_num_est_per_year)
# forecasted_earnings
stock_database_quartiled_feps_table[2,1]<-mean(first_partition$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,2]<-mean(quartile_one$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,3]<-mean(quartile_two$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,4]<-mean(quartile_three$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,5]<-mean(quartile_four$average_forecasted_earnings)
# Actual Earnings
stock_database_quartiled_feps_table[3,1]<-mean(first_partition$actual_eps)
stock_database_quartiled_feps_table[3,2]<-mean(quartile_one$actual_eps)
stock_database_quartiled_feps_table[3,3]<-mean(quartile_two$actual_eps)
stock_database_quartiled_feps_table[3,4]<-mean(quartile_three$actual_eps)
stock_database_quartiled_feps_table[3,5]<-mean(quartile_four$actual_eps)
# FEPS
stock_database_quartiled_feps_table[4,1]<-mean(first_partition_jan$scaled_feps)
stock_database_quartiled_feps_table[4,2]<-mean(base_predict_month_quartile_one$scaled_feps)
stock_database_quartiled_feps_table[4,3]<-mean(base_predict_month_quartile_two$scaled_feps)
stock_database_quartiled_feps_table[4,4]<-mean(base_predict_month_quartile_three$scaled_feps)
stock_database_quartiled_feps_table[4,5]<-mean(base_predict_month_quartile_four$scaled_feps)
# Price 
stock_database_quartiled_feps_table[5,1]<-mean(first_partition$price)
stock_database_quartiled_feps_table[5,2]<-mean(quartile_one$price)
stock_database_quartiled_feps_table[5,3]<-mean(quartile_two$price)
stock_database_quartiled_feps_table[5,4]<-mean(quartile_three$price)
stock_database_quartiled_feps_table[5,5]<-mean(quartile_four$price)
# Market Cap 
stock_database_quartiled_feps_table[6,1]<-mean(first_partition$market_capitalization)
stock_database_quartiled_feps_table[6,2]<-mean(quartile_one$market_capitalization)
stock_database_quartiled_feps_table[6,3]<-mean(quartile_two$market_capitalization)
stock_database_quartiled_feps_table[6,4]<-mean(quartile_three$market_capitalization)
stock_database_quartiled_feps_table[6,5]<-mean(quartile_four$market_capitalization)

# Save the tables
write.csv(stock_database_quartiled_feps_table,"bull_stock_database_quartiled_feps_table.csv")
```
# Bear
```{r}
first_partition<-database_v1 %>% filter(bull=='false')
first_partition_jan<-january_only_database %>% filter(bull=='false')

x <- c("Overall","Q1","Q2","Q3","Q4")
y <- c("number_of_analysts","forecasted_earnings","actual_earnings","scaled_forecast","price","market_value")
# Creation of the table 

# Define FEPS Table
stock_database_quartiled_feps_table <- data.frame(matrix(ncol = 5, nrow = 6))
colnames(stock_database_quartiled_feps_table) <- x
rownames(stock_database_quartiled_feps_table)<-y

# Define the quartiles
quartile_one <-first_partition%>% filter(quartile_feps==1)
quartile_two<-first_partition %>% filter (quartile_feps==2)
quartile_three<-first_partition %>% filter (quartile_feps==3)
quartile_four<-first_partition %>% filter (quartile_feps==4)
# Define the quartiles as of January
base_predict_month_quartile_one <-first_partition_jan %>% filter (quartile_feps==1)
base_predict_month_quartile_two <-first_partition_jan %>% filter (quartile_feps==2)
base_predict_month_quartile_three <-first_partition_jan %>% filter (quartile_feps==3)
base_predict_month_quartile_four <-first_partition_jan %>% filter (quartile_feps==4)
# Number of Analysts
# stock_database_quartiled_feps_table[1,1]<-mean(distinct_quartiled_1980_1996$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,2]<-mean(quartile_one$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,3]<-mean(quartile_two$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,4]<-mean(quartile_three$number_of_analyst_predictions)
# stock_database_quartiled_feps_table[1,5]<-mean(quartile_four$number_of_analyst_predictions)
stock_database_quartiled_feps_table[1,1]<-mean(first_partition$max_num_est_per_year)
stock_database_quartiled_feps_table[1,2]<-mean(quartile_one$max_num_est_per_year)
stock_database_quartiled_feps_table[1,3]<-mean(quartile_two$max_num_est_per_year)
stock_database_quartiled_feps_table[1,4]<-mean(quartile_three$max_num_est_per_year)
stock_database_quartiled_feps_table[1,5]<-mean(quartile_four$max_num_est_per_year)
# forecasted_earnings
stock_database_quartiled_feps_table[2,1]<-mean(first_partition$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,2]<-mean(quartile_one$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,3]<-mean(quartile_two$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,4]<-mean(quartile_three$average_forecasted_earnings)
stock_database_quartiled_feps_table[2,5]<-mean(quartile_four$average_forecasted_earnings)
# Actual Earnings
stock_database_quartiled_feps_table[3,1]<-mean(first_partition$actual_eps)
stock_database_quartiled_feps_table[3,2]<-mean(quartile_one$actual_eps)
stock_database_quartiled_feps_table[3,3]<-mean(quartile_two$actual_eps)
stock_database_quartiled_feps_table[3,4]<-mean(quartile_three$actual_eps)
stock_database_quartiled_feps_table[3,5]<-mean(quartile_four$actual_eps)
# FEPS
stock_database_quartiled_feps_table[4,1]<-mean(first_partition_jan$scaled_feps)
stock_database_quartiled_feps_table[4,2]<-mean(base_predict_month_quartile_one$scaled_feps)
stock_database_quartiled_feps_table[4,3]<-mean(base_predict_month_quartile_two$scaled_feps)
stock_database_quartiled_feps_table[4,4]<-mean(base_predict_month_quartile_three$scaled_feps)
stock_database_quartiled_feps_table[4,5]<-mean(base_predict_month_quartile_four$scaled_feps)
# Price 
stock_database_quartiled_feps_table[5,1]<-mean(first_partition$price)
stock_database_quartiled_feps_table[5,2]<-mean(quartile_one$price)
stock_database_quartiled_feps_table[5,3]<-mean(quartile_two$price)
stock_database_quartiled_feps_table[5,4]<-mean(quartile_three$price)
stock_database_quartiled_feps_table[5,5]<-mean(quartile_four$price)
# Market Cap 
stock_database_quartiled_feps_table[6,1]<-mean(first_partition$market_capitalization)
stock_database_quartiled_feps_table[6,2]<-mean(quartile_one$market_capitalization)
stock_database_quartiled_feps_table[6,3]<-mean(quartile_two$market_capitalization)
stock_database_quartiled_feps_table[6,4]<-mean(quartile_three$market_capitalization)
stock_database_quartiled_feps_table[6,5]<-mean(quartile_four$market_capitalization)

# Save the tables
write.csv(stock_database_quartiled_feps_table,"bear_stock_database_quartiled_feps_table.csv")
```
# STats for george
```{r}
database_v1
length(unique(database_v1$ticker))
length(unique(database_v1$two_digit_sich))
first_partition<-database_v1 %>% filter(year_analyst_predict<=1996)
first_partition
length(unique(first_partition$ticker))
length(unique(first_partition$two_digit_sich))
second_partition<-database_v1 %>% filter(year_analyst_predict>1996)
second_partition
length(unique(second_partition$ticker))
length(unique(second_partition$two_digit_sich))
```

